fixtures:
  forge_modules:
    stdlib:
      repo: puppetlabs/stdlib
    epel:
      repo: puppet/epel
    apt:
      repo: puppetlabs/apt
    inifile:
      repo: puppetlabs/inifile
    firewall:
      repo: puppetlabs/firewall
    yumrepo_core:
      repo: puppetlabs/yumrepo_core
    python:
      repo: puppet/python
  symlinks:
    globus: "#{source_dir}"
