---
.github/workflows/ci.yaml:
  acceptance_matrix:
    set:
      - el7
      - el8
      - ---el9
      - debian-11
      - ubuntu-2004
      - ubuntu-2204
    puppet:
      - puppet7
      - puppet8
.rubocop.yml:
  profiles:
    strict:
      configs:
        RSpec/RepeatedExampleGroupBody:
          Enabled: false
        RSpec/RepeatedDescription:
          Enabled: false
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
spec/acceptance/nodesets/el7.yml:
  extra_commands:
    - 'echo "LC_ALL=en_US.UTF-8" >> /etc/environment'
    - 'echo "LANG=en_US.UTF-8" > /etc/locale.conf'
