---
.github/workflows/ci.yaml:
  acceptance_matrix:
    set:
      - el7
      - el8
      - ---el9
      - debian-10
      - ubuntu-1804
      - ubuntu-2004
    puppet:
      - puppet6
      - puppet7
.rubocop.yml:
  profiles:
    strict:
      configs:
        RSpec/RepeatedExampleGroupBody:
          Enabled: false
        RSpec/RepeatedDescription:
          Enabled: false
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
spec/acceptance/nodesets/el9.yml:
  delete: true
spec/acceptance/nodesets/debian-11.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-2204.yml:
  delete: true
spec/acceptance/nodesets/centos-7.yml:
  extra_commands:
    - 'echo "LC_ALL=en_US.UTF-8" >> /etc/environment'
    - 'echo "LANG=en_US.UTF-8" > /etc/locale.conf'
